version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - myfun-node_modules:/workspace/frontend/my-fun/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - windir # Defined on Windows but not on other platforms
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - '5432:5432'
    volumes:
      - myfun-postgres:/var/lib/postgresql/data

volumes:
  myfun-node_modules:
  myfun-postgres: